---
- name: Restart zookeeper
  service:
    name: "zookeeper"
    state: "restarted"

- name: Restart mariadb
  service:
    name: "mysql"
    state: "restarted"

- name: Restart kafka
  service:
    name: "kafka"
    state: "restarted"

- name: Restart influxdb
  service:
    name: "influxdb"
    state: "restarted"

- name: Restart storm nimbus
  service:
    name: "storm-nimbus"
    state: "restarted"

- name: Restart storm supervisor
  service:
    name: "storm-supervisor"
    state: "restarted"

- name: Restart monasca-api
  service:
    name: "monasca-api"
    state: "restarted"

- name: Restart monasca-persister
  service:
    name: "monasca-persister"
    state: "restarted"

- name: Restart monasca-notification
  service:
    name: "monasca-notification"
    state: "restarted"

- name: Restart monasca-thresh
  service:
    name: "monasca-thresh"
    state: "restarted"
