---
# Copyright 2016 LSD/UFCG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Monasca
monasca_common_git_repo: "https://git.openstack.org/openstack/monasca-common.git"
monasca_api_git_repo: "https://git.openstack.org/openstack/monasca-api.git"
monasca_persister_git_repo: "https://git.openstack.org/openstack/monasca-persister.git"
monasca_notification_git_repo: "https://git.openstack.org/openstack/monasca-notification.git"
monasca_thresh_git_repo: "https://git.openstack.org/openstack/monasca-thresh.git"
monasca_ui_git_repo: "https://git.openstack.org/openstack/monasca-ui.git"
monasca_client_git_repo: "https://git.openstack.org/openstack/python-monascaclient.git"
monasca_git_branch: "master"

## Grafana
grafana_plugins_git_repo: "https://github.com/twc-openstack/grafana-plugins.git"
grafana_plugins_git_branch: "v2.6.0"
grafana_git_repo: "https://github.com/twc-openstack/grafana.git"
grafana_git_branch: "v2.6.0-keystone"

## Keystone
keystone_ip_address: "127.0.0.1"
os_username: "admin"
os_password: "secretadmin"
os_project_name: "admin"

## Database
mysql_root_pass: "secretdatabase"

## InfluxDB
influxdb_version: "0.9.5"

## Kafka
base_kafka_version: "0.8.1.1"
kafka_version: "2.9.2-{{ base_kafka_version }}"

## Storm
storm_version: "1.0.1"
storm_logback_dir: "log4j2"

## NTP
ntp_servers:
  - ntp.lsd.ufcg.edu.br

## System info
monasca_system_user_name: monasca
monasca_system_group_name: monasca
monasca_system_shell: /bin/false
monasca_system_comment: monasca system user
monasca_system_user_home: "/var/lib/{{ monasca_system_user_name }}"

pip_install_options: ""

monasca_required_pip_packages:
  - virtualenv
  - virtualenv-tools
  - httplib2

# Common pip packages
monasca_pip_packages:
  - python-keystoneclient
  - keystoneauth1
  - simport
