- hosts: devstack
  vars:
    - devstack_branch: "stable/mitaka"

  pre_tasks:
    - name: apt-get update
      become: yes
      apt: update_cache=yes
      ignore_errors: true
      tags:
        - git-install
    - name: Install git
      become: yes
      apt: name=git
      tags:
        - git-install

  tasks:
    - name: Clone devstack branch "{{devstack_branch}}"
      git:
        repo: https://git.openstack.org/openstack-dev/devstack
        version: "{{devstack_branch}}"
        dest: "/home/{{ansible_user}}/devstack"
        depth: 1
        update: no
      tags:
        - git-clone

    - name: Copy devstack local.conf
      copy: src=local.conf dest=/home/{{ansible_user}}/devstack/
      tags:
        - devstack

    - name: Is devstack running?
      shell: screen -ls | egrep -q "\.stack"
      args:
        chdir: "/home/{{ansible_user}}/devstack"
      register: is_devstack_running
      ignore_errors: true
      tags:
        - devstack

    - name: Install Stack devstack
      command: "./stack.sh chdir=/home/{{ansible_user}}/devstack"
      tags:
        - devstack
      when: is_devstack_running.rc > 0
