- name: Install Monasca Agent
  hosts: monasca-agent
  user: ubuntu
  become: yes
  roles:
    - { role: "os_monasca_agent", tags: [ "os-monasca-agent" ] }
  vars:
    - keystone_ip_address: "{{ groups['devstack'][0] }}"
    - monasca_ip_address: "{{ groups['monasca'][0] }}"
