---
- name: Drop Zookeeper Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items:
    - src: "zookeeper/zoo.cfg.j2"
      dest: "/etc/zookeeper/conf/zoo.cfg"
      owner: "root"
      group: "root"
    - src: "zookeeper/myid.j2"
      dest: "/etc/zookeeper/conf/myid"
      owner: "root"
      group: "root"
    - src: "zookeeper/environment.j2"
      dest: "/etc/zookeeper/conf/environment"
      owner: "root"
      group: "root"
    - src: "zookeeper/log4j.properties.j2"
      dest: "/etc/zookeeper/conf/log4j.properties"
      owner: "root"
      group: "root"
  register: zookeeper_config
  tags:
    - zookeeper-config
    - monasca-install-zookeeper

- name: Restart zookeeper
  service:
    name: "zookeeper"
    state: "restarted"
  when: zookeeper_config.changed
  tags:
    - zookeeper-restart
    - monasca-install-zookeeper
