---
- name: Download golang
  get_url:
    url: "https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz"
    dest: "/root/go1.5.2.linux-amd64.tar.gz"
    mode: 0440
  tags:
    - monasca-golang-download
    - monasca-install-grafana

- name: Unarchive golang
  unarchive:
    src: "/root/go1.5.2.linux-amd64.tar.gz"
    dest: "/usr/local"
    creates: "/usr/local/go"
    copy: "no"
  tags:
    - monasca-golang-unarchive
    - monasca-install-grafana

- name: Clone grafana git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "/opt/cloned-repos/{{ item.dest }}"
    version: "{{ item.version }}"
    force: "yes"
  with_items:
    - repo: "{{ grafana_plugins_git_repo }}"
      dest: "grafana-plugins"
      version: "v2.6.0"
    - repo: "{{ grafana_git_repo }}"
      dest: "grafana"
      version: "v2.6.0-keystone"
  tags:
    - monasca-grafana-clone-repos
    - monasca-install-grafana

- name: Copy grafana install script
  copy: 
    src: "install_grafana.sh"
    dest: "/opt/grafana-build/install_grafana.sh"
    mode: "0750"
  register: grafana_script
  tags:
    - monasca-grafana-script
    - monasca-install-grafana

- name: Install grafana 
  command: "./install_grafana.sh"
  args:
    chdir: "/opt/grafana-build"
  when: grafana_script.changed
  tags:
    - monasca-install-grafana

- name: Drop grafana Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - src: "grafana/grafana-server.j2"
      dest: "/etc/init.d/grafana-server"
      owner: "root"
      group: "root"
      mode: "0775"
    - src: "grafana/grafana.ini.j2"
      dest: "/etc/grafana/grafana.ini"
      owner: "root"
      group: "root"
  register: grafana_config
  tags:
    - monasca-grafana-config
    - monasca-install-grafana

- name: Restart grafana
  service:
    name: "grafana-server"
    state: "restarted"
  when: grafana_config.changed
  tags:
    - monasca-grafana-restart
    - monasca-install-grafana
