---
- name: Create monasca-persister tarball
  command: "/opt/venvs/monasca-persister/bin/python setup.py sdist"
  args:
    chdir: "/opt/cloned-repos/monasca-persister"
  tags:
    - monasca-persister-tarball
    - monasca-install-persister

- name: Get tarball file name
  shell: "ls -td /opt/cloned-repos/monasca-persister/dist/monasca-persister-*.tar.gz | head -1"
  register: tarball
  tags:
    - monasca-persister-install
    - monasca-install-persister

- name: Install monasca-persister
  pip:
    name: "file://{{ tarball.stdout }}"
    virtualenv: "/opt/venvs/monasca-persister"
  tags:
    - monasca-persister-install
    - monasca-install-persister

- name: Drop monasca-persister Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "monasca-persister/monasca-persister-init.conf.j2"
      dest: "/etc/init/monasca-persister.conf"
      owner: "root"
      group: "root"
      mode: "0744"
    - src: "monasca-persister/persister.conf.j2"
      dest: "/etc/monasca/persister.conf"
      owner: "mon-persister"
      group: "monasca"
      mode: "0640"
    - src: "monasca-persister/persister-config.yml.j2"
      dest: "/etc/monasca/persister-config.yml"
      owner: "mon-persister"
      group: "monasca"
      mode: "0640"
  tags:
    - monasca-persister-config
    - monasca-install-persister

- name: Restart monasca-persister
  service:
    name: "monasca-persister"
    state: "restarted"
  tags:
    - monasca-persister-restart
    - monasca-install-persister
