---
- name: Download nodejs apt source script
  get_url:
    url: "https://deb.nodesource.com/setup_4.x"
    dest: "/root/nodejs-setup_4.x"
    mode: 0750
  register: nodejs_apt
  tags:
    - monasca-nodejs

- name: Run nodejs script
  shell: "/root/nodejs-setup_4.x"
  when: nodejs_apt.changed
  tags:
    - monasca-nodejs

- name: Check apt last update file
  stat:
    path: /var/cache/apt
  register: apt_cache_stat

- name: Update apt if needed
  apt:
    update_cache: yes
  when: "ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > {{cache_timeout}}"

- name: Remove Maven2
  apt:
    pkg: maven2
    state: absent

- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: monasca_apt_packages
