---
- name: Create monasca-agent tarball
  command: "/opt/venvs/monasca-agent/bin/python setup.py sdist"
  args:
    chdir: "/opt/cloned-repos/monasca-agent"
  tags:
    - monasca-agent-tarball
    - monasca-install-agent

- name: Get tarball file name
  shell: "ls -td /opt/cloned-repos/monasca-agent/dist/monasca-agent-*.tar.gz | head -1"
  register: tarball
  tags:
    - monasca-install-agent

- name: Install monasca-agent
  pip:
    name: "file://{{ tarball.stdout }}"
    virtualenv: "/opt/venvs/monasca-agent"
  tags:
    - monasca-install-agent

- name: Drop monasca-agent config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "host_alive.yaml.j2"
      dest: "/etc/monasca/agent/conf.d/host_alive.yaml"
      owner: "root"
      group: "root"
      mode: "0744"
    - src: "monasca-reconfigure.j2"
      dest: "/usr/local/bin/monasca-reconfigure"
      owner: "root"
      group: "root"
      mode: "0750"
  notify:
    - Restart monasca-agent
  tags:
    - monasca-agent-config
    - monasca-install-agent

- name: Remove monasca vcenter plugin
  file:
    path: "/opt/venvs/monasca-agent/local/lib/python2.7/site-packages/monasca_setup/detection/plugins/vcenter.py"
    state: "absent"
  tags:
    - monasca-rm-vcenter
    - monasca-install-agent

- name: Remove monasca rabbitmq plugin
  file:
    path: "/opt/venvs/monasca-agent/local/lib/python2.7/site-packages/monasca_setup/detection/plugins/rabbitmq.py"
    state: "absent"
  when: monasca_git_branch == "stable/mitaka"
  tags:
    - monasca-rm-vcenter
    - monasca-install-agent

- name: Drop mysql config
  template:
    src: "my.cnf.j2"
    dest: "/root/.my.cnf"
  when: "inventory_hostname in groups['devstack']"
  tags:
    - monasca-mysql-plugin
    - monasca-install-agent

- name: Run monasca-reconfigure
  command: "/usr/local/bin/monasca-reconfigure"
  tags:
    - monasca-agent-reconfigure
    - monasca-install-agent
